// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.201
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RegistryExplorer
{
    static class Vsix
    {
        public const string Id = "29464950-087c-4fb6-9fdd-bab0fb71d68f";
        public const string Name = "Registry Explorer";
        public const string Description = @"Provides a tool window that shows the Visual Studio registry hive";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "registry, vsix";
    }
}
