// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.201
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RegistryExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidRegistryEplorerPackageString = "f69ea5b6-7d1c-48e1-aa62-dfee8a21f1a6";
        public const string guidRegistryEplorerPackageCmdSetString = "e55740b7-6c7f-4ff7-9235-4082c8fc3cde";
        public static Guid guidRegistryEplorerPackage = new Guid(guidRegistryEplorerPackageString);
        public static Guid guidRegistryEplorerPackageCmdSet = new Guid(guidRegistryEplorerPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowRegistryExplorerId = 0x0100;
    }
}
